name: Lint and build
on: push
jobs:
  build:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
      - run: npm ci
      - run: npm run lint
      - run: npm run build
